
package com.haier.QuerySupplierBalanceFromGVS;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "QuerySupplierBalanceFromGVS", targetNamespace = "http://www.example.org/QuerySupplierBalanceFromGVS/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface QuerySupplierBalanceFromGVS {


    /**
     * 
     * @param input
     * @return
     *     returns java.util.List<com.haier.QuerySupplierBalanceFromGVS.ZFIINTLIFNRYEOUT>
     */
    @WebMethod(operationName = "QuerySupplierBalanceFromGVS", action = "http://www.example.org/QuerySupplierBalanceFromGVS/QuerySupplierBalanceFromGVS")
    @WebResult(name = "OUTPUT", targetNamespace = "")
    @RequestWrapper(localName = "QuerySupplierBalanceFromGVS", targetNamespace = "http://www.example.org/QuerySupplierBalanceFromGVS/", className = "com.haier.QuerySupplierBalanceFromGVS.QuerySupplierBalanceFromGVS_Type")
    @ResponseWrapper(localName = "QuerySupplierBalanceFromGVSResponse", targetNamespace = "http://www.example.org/QuerySupplierBalanceFromGVS/", className = "com.haier.QuerySupplierBalanceFromGVS.QuerySupplierBalanceFromGVSResponse")
    public List<ZFIINTLIFNRYEOUT> querySupplierBalanceFromGVS(
        @WebParam(name = "INPUT", targetNamespace = "")
        List<ZFIINTLIFNRYEIN> input);

}
