
package com.haier.QuerySupplierBalanceFromGVS;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "QuerySupplierBalanceFromGVS", targetNamespace = "http://www.example.org/QuerySupplierBalanceFromGVS/", wsdlLocation = "./QuerySupplierBalanceFromGVS/QuerySupplierBalanceFromGVS.wsdl")
public class QuerySupplierBalanceFromGVS_Service
    extends Service
{

    private final static URL QUERYSUPPLIERBALANCEFROMGVS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.haier.QuerySupplierBalanceFromGVS.QuerySupplierBalanceFromGVS_Service.class.getName());

    static {
        URL url = null;
        try {
            url = QuerySupplierBalanceFromGVS_Service.class.getResource("/wsdl/QuerySupplierBalanceFromGVS.wsdl");
        } catch (Exception e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:///Users/Effet/terminus/snz/snz-eai-api/src/main/java/com/haier/QuerySupplierBalanceFromGVS/QuerySupplierBalanceFromGVS.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        QUERYSUPPLIERBALANCEFROMGVS_WSDL_LOCATION = url;
    }

    public QuerySupplierBalanceFromGVS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QuerySupplierBalanceFromGVS_Service() {
        super(QUERYSUPPLIERBALANCEFROMGVS_WSDL_LOCATION, new QName("http://www.example.org/QuerySupplierBalanceFromGVS/", "QuerySupplierBalanceFromGVS"));
    }

    /**
     * 
     * @return
     *     returns QuerySupplierBalanceFromGVS
     */
    @WebEndpoint(name = "QuerySupplierBalanceFromGVSSOAP")
    public QuerySupplierBalanceFromGVS getQuerySupplierBalanceFromGVSSOAP() {
        return super.getPort(new QName("http://www.example.org/QuerySupplierBalanceFromGVS/", "QuerySupplierBalanceFromGVSSOAP"), QuerySupplierBalanceFromGVS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuerySupplierBalanceFromGVS
     */
    @WebEndpoint(name = "QuerySupplierBalanceFromGVSSOAP")
    public QuerySupplierBalanceFromGVS getQuerySupplierBalanceFromGVSSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/QuerySupplierBalanceFromGVS/", "QuerySupplierBalanceFromGVSSOAP"), QuerySupplierBalanceFromGVS.class, features);
    }

}
