
package com.haier.SelectInfoFromMDM;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SelectInfoFromMDM", targetNamespace = "http://www.example.org/SelectInfoFromMDM/", wsdlLocation = "http://10.135.1.198:7001//EAI/service/MDM/SelectInfoFromMDM/SelectInfoFromMDM?wsdl")
public class SelectInfoFromMDM_Service
    extends Service
{

    private final static URL SELECTINFOFROMMDM_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.haier.SelectInfoFromMDM.SelectInfoFromMDM_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.haier.SelectInfoFromMDM.SelectInfoFromMDM_Service.class.getResource(".");
            url = new URL(baseUrl, "http://10.135.1.198:7001//EAI/service/MDM/SelectInfoFromMDM/SelectInfoFromMDM?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.135.1.198:7001//EAI/service/MDM/SelectInfoFromMDM/SelectInfoFromMDM?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SELECTINFOFROMMDM_WSDL_LOCATION = url;
    }

    public SelectInfoFromMDM_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SelectInfoFromMDM_Service() {
        super(SELECTINFOFROMMDM_WSDL_LOCATION, new QName("http://www.example.org/SelectInfoFromMDM/", "SelectInfoFromMDM"));
    }

    /**
     * 
     * @return
     *     returns SelectInfoFromMDM
     */
    @WebEndpoint(name = "SelectInfoFromMDMSOAP")
    public SelectInfoFromMDM getSelectInfoFromMDMSOAP() {
        return super.getPort(new QName("http://www.example.org/SelectInfoFromMDM/", "SelectInfoFromMDMSOAP"), SelectInfoFromMDM.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SelectInfoFromMDM
     */
    @WebEndpoint(name = "SelectInfoFromMDMSOAP")
    public SelectInfoFromMDM getSelectInfoFromMDMSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/SelectInfoFromMDM/", "SelectInfoFromMDMSOAP"), SelectInfoFromMDM.class, features);
    }

}
