
package com.haier.SelectInfoFromMDM;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SelectInfoFromMDM", targetNamespace = "http://www.example.org/SelectInfoFromMDM/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SelectInfoFromMDM {


    /**
     * 
     * @param in
     * @return
     *     returns com.haier.SelectInfoFromMDM.SelectInfoFromMDMOPResponse.Output
     */
    @WebMethod(operationName = "SelectInfoFromMDM_OP", action = "http://www.example.org/SelectInfoFromMDM/SelectInfoFromMDM_OP")
    @WebResult(name = "Output", targetNamespace = "")
    @RequestWrapper(localName = "SelectInfoFromMDM_OP", targetNamespace = "http://www.example.org/SelectInfoFromMDM/", className = "com.haier.SelectInfoFromMDM.SelectInfoFromMDMOP")
    @ResponseWrapper(localName = "SelectInfoFromMDM_OPResponse", targetNamespace = "http://www.example.org/SelectInfoFromMDM/", className = "com.haier.SelectInfoFromMDM.SelectInfoFromMDMOPResponse")
    public com.haier.SelectInfoFromMDM.SelectInfoFromMDMOPResponse.Output selectInfoFromMDMOP(
        @WebParam(name = "in", targetNamespace = "")
        InType in);

}
