
package org.example.receiveclaiminfofromgvs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ReceiveClaimInfoFromGVS", targetNamespace = "http://www.example.org/ReceiveClaimInfoFromGVS/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReceiveClaimInfoFromGVS {


    /**
     * 
     * @param tINPUT
     * @return
     *     returns org.example.receiveclaiminfofromgvs.OutType
     */
    @WebMethod(operationName = "ReceiveClaimInfoFromGVS", action = "http://www.example.org/ReceiveClaimInfoFromGVS/ReceiveClaimInfoFromGVS")
    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "ReceiveClaimInfoFromGVS", targetNamespace = "http://www.example.org/ReceiveClaimInfoFromGVS/", className = "org.example.receiveclaiminfofromgvs.ReceiveClaimInfoFromGVS_Type")
    @ResponseWrapper(localName = "ReceiveClaimInfoFromGVSResponse", targetNamespace = "http://www.example.org/ReceiveClaimInfoFromGVS/", className = "org.example.receiveclaiminfofromgvs.ReceiveClaimInfoFromGVSResponse")
    public OutType receiveClaimInfoFromGVS(
        @WebParam(name = "T_INPUT", targetNamespace = "")
        List<ZSPJHINPUT2> tINPUT);

}
