
package com.haier.GetQuotaInfoFromGVSToEBS;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "GetQuotaInfoFromGVSToJHPT", targetNamespace = "http://www.example.org/GetQuotaInfoFromGVSToJHPT/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetQuotaInfoFromGVSToJHPT {


    /**
     * 
     * @param zstrQUOINFO
     * @param inputs
     * @param zstrPRICEINFO
     */
    @WebMethod(operationName = "GetQuotaInfoFromGVSToJHPT_OP", action = "http://www.example.org/GetQuotaInfoFromGVSToJHPT/GetQuotaInfoFromGVSToJHPT_OP")
    @RequestWrapper(localName = "GetQuotaInfoFromGVSToJHPT_OP", targetNamespace = "http://www.example.org/GetQuotaInfoFromGVSToJHPT/", className = "com.haier.GetQuotaInfoFromGVSToEBS.GetQuotaInfoFromGVSToJHPTOP")
    @ResponseWrapper(localName = "GetQuotaInfoFromGVSToJHPT_OPResponse", targetNamespace = "http://www.example.org/GetQuotaInfoFromGVSToJHPT/", className = "com.haier.GetQuotaInfoFromGVSToEBS.GetQuotaInfoFromGVSToJHPTOPResponse")
    public void getQuotaInfoFromGVSToJHPTOP(
        @WebParam(name = "Inputs", targetNamespace = "")
        List<InputsType> inputs,
        @WebParam(name = "ZSTR_QUO_INFO", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<List<ZSTRQUOINFOType>> zstrQUOINFO,
        @WebParam(name = "ZSTR_PRICE_INFO", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<List<ZSTRPRICEINFOType>> zstrPRICEINFO);

}
