
package com.haier.GetQuotaInfoFromGVSToEBS;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "GetQuotaInfoFromGVSToJHPT", targetNamespace = "http://www.example.org/GetQuotaInfoFromGVSToJHPT/", wsdlLocation = "/wsdl/GetQuotaInfoFromGVSToEBS.wsdl")
public class GetQuotaInfoFromGVSToJHPT_Service
    extends Service
{

    private final static URL GETQUOTAINFOFROMGVSTOJHPT_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.haier.GetQuotaInfoFromGVSToEBS.GetQuotaInfoFromGVSToJHPT_Service.class.getName());

    static {
        URL url = null;
        try {
            url = GetQuotaInfoFromGVSToJHPT_Service.class.getResource("/wsdl/GetQuotaInfoFromGVSToEBS.wsdl");
        } catch (Exception e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:///Users/luyuzhou/work/git/snz/snz-eai-api/src/main/resources/wsdl/GetQuotaInfoFromGVSToEBS.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        GETQUOTAINFOFROMGVSTOJHPT_WSDL_LOCATION = url;
    }

    public GetQuotaInfoFromGVSToJHPT_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetQuotaInfoFromGVSToJHPT_Service() {
        super(GETQUOTAINFOFROMGVSTOJHPT_WSDL_LOCATION, new QName("http://www.example.org/GetQuotaInfoFromGVSToJHPT/", "GetQuotaInfoFromGVSToJHPT"));
    }

    /**
     * 
     * @return
     *     returns GetQuotaInfoFromGVSToJHPT
     */
    @WebEndpoint(name = "GetQuotaInfoFromGVSToJHPTSOAP")
    public GetQuotaInfoFromGVSToJHPT getGetQuotaInfoFromGVSToJHPTSOAP() {
        return super.getPort(new QName("http://www.example.org/GetQuotaInfoFromGVSToJHPT/", "GetQuotaInfoFromGVSToJHPTSOAP"), GetQuotaInfoFromGVSToJHPT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetQuotaInfoFromGVSToJHPT
     */
    @WebEndpoint(name = "GetQuotaInfoFromGVSToJHPTSOAP")
    public GetQuotaInfoFromGVSToJHPT getGetQuotaInfoFromGVSToJHPTSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/GetQuotaInfoFromGVSToJHPT/", "GetQuotaInfoFromGVSToJHPTSOAP"), GetQuotaInfoFromGVSToJHPT.class, features);
    }

}
