
package com.haier.TransCashPledgeFromGVS;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TransCashPledgeFrom", targetNamespace = "http://www.example.org/TransCashPledgeFrom/", wsdlLocation = "wsdl/TransCashPledgeFromGVS.wsdl")
public class TransCashPledgeFrom_Service
    extends Service
{

    private final static URL TRANSCASHPLEDGEFROM_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.haier.TransCashPledgeFromGVS.TransCashPledgeFrom_Service.class.getName());

    static {
        TRANSCASHPLEDGEFROM_WSDL_LOCATION = TransCashPledgeFrom_Service.class.getResource("/wsdl/TransCashPledgeFromGVS.wsdl");
    }

    public TransCashPledgeFrom_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransCashPledgeFrom_Service() {
        super(TRANSCASHPLEDGEFROM_WSDL_LOCATION, new QName("http://www.example.org/TransCashPledgeFrom/", "TransCashPledgeFrom"));
    }

    /**
     * 
     * @return
     *     returns TransCashPledgeFrom
     */
    @WebEndpoint(name = "TransCashPledgeFromSOAP")
    public TransCashPledgeFrom getTransCashPledgeFromSOAP() {
        return super.getPort(new QName("http://www.example.org/TransCashPledgeFrom/", "TransCashPledgeFromSOAP"), TransCashPledgeFrom.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransCashPledgeFrom
     */
    @WebEndpoint(name = "TransCashPledgeFromSOAP")
    public TransCashPledgeFrom getTransCashPledgeFromSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/TransCashPledgeFrom/", "TransCashPledgeFromSOAP"), TransCashPledgeFrom.class, features);
    }

}
