
package com.haier.TransCashPledgeFromGVS;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TransCashPledgeFrom", targetNamespace = "http://www.example.org/TransCashPledgeFrom/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TransCashPledgeFrom {


    /**
     * 
     * @param eaiMessage
     * @param itabLOG
     */
    @WebMethod(operationName = "TransCashPledgeFrom", action = "http://www.example.org/TransCashPledgeFrom/TransCashPledgeFrom")
    @RequestWrapper(localName = "TransCashPledgeFrom", targetNamespace = "http://www.example.org/TransCashPledgeFrom/", className = "com.haier.TransCashPledgeFromGVS.TransCashPledgeFrom_Type")
    @ResponseWrapper(localName = "TransCashPledgeFromResponse", targetNamespace = "http://www.example.org/TransCashPledgeFrom/", className = "com.haier.TransCashPledgeFromGVS.TransCashPledgeFromResponse")
    public void transCashPledgeFrom(
        @WebParam(name = "ITAB_LOG", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<List<ZFIMKZYLOG>> itabLOG,
        @WebParam(name = "EAIMessage", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eaiMessage);

}
