
package org.example.transpricegoodsinfotohgvs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TransPriceGoodsInfoToHGVS", targetNamespace = "http://www.example.org/TransPriceGoodsInfoToHGVS/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TransPriceGoodsInfoToHGVS {


    /**
     * 
     * @param datain
     * @return
     *     returns org.example.transpricegoodsinfotohgvs.OutType
     */
    @WebMethod(operationName = "TransPriceGoodsInfoToHGVS", action = "http://www.example.org/TransPriceGoodsInfoToHGVS/TransPriceGoodsInfoToHGVS")
    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "TransPriceGoodsInfoToHGVS", targetNamespace = "http://www.example.org/TransPriceGoodsInfoToHGVS/", className = "org.example.transpricegoodsinfotohgvs.TransPriceGoodsInfoToHGVS_Type")
    @ResponseWrapper(localName = "TransPriceGoodsInfoToHGVSResponse", targetNamespace = "http://www.example.org/TransPriceGoodsInfoToHGVS/", className = "org.example.transpricegoodsinfotohgvs.TransPriceGoodsInfoToHGVSResponse")
    public OutType transPriceGoodsInfoToHGVS(
            @WebParam(name = "DATAIN", targetNamespace = "")
            List<ZDWHJHPT> datain);

}
