
package org.example.sendclaiminfotogvs;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SendClaimInfoToGVS", targetNamespace = "http://www.example.org/SendClaimInfoToGVS/", wsdlLocation = "classpath:/wsdl/SendClaimInfoToGVS.wsdl")
public class SendClaimInfoToGVS_Service
    extends Service
{

    private final static URL SENDCLAIMINFOTOGVS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.example.sendclaiminfotogvs.SendClaimInfoToGVS_Service.class.getName());

    static {
        URL url = null;
        try {
            url = SendClaimInfoToGVS_Service.class.getResource("/wsdl/SendClaimInfoToGVS.wsdl");
        } catch (Exception e) {
            logger.warning("Failed to create URL for the wsdl Location: 'classpath:/wsdl/SendClaimInfoToGVS.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SENDCLAIMINFOTOGVS_WSDL_LOCATION = url;
    }

    public SendClaimInfoToGVS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SendClaimInfoToGVS_Service() {
        super(SENDCLAIMINFOTOGVS_WSDL_LOCATION, new QName("http://www.example.org/SendClaimInfoToGVS/", "SendClaimInfoToGVS"));
    }

    /**
     * 
     * @return
     *     returns SendClaimInfoToGVS
     */
    @WebEndpoint(name = "SendClaimInfoToGVSSOAP")
    public SendClaimInfoToGVS getSendClaimInfoToGVSSOAP() {
        return super.getPort(new QName("http://www.example.org/SendClaimInfoToGVS/", "SendClaimInfoToGVSSOAP"), SendClaimInfoToGVS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SendClaimInfoToGVS
     */
    @WebEndpoint(name = "SendClaimInfoToGVSSOAP")
    public SendClaimInfoToGVS getSendClaimInfoToGVSSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/SendClaimInfoToGVS/", "SendClaimInfoToGVSSOAP"), SendClaimInfoToGVS.class, features);
    }

}
