
package org.example.transstandardcredittosrm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TransStandardCreditToSRM", targetNamespace = "http://www.example.org/TransStandardCreditToSRM/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TransStandardCreditToSRM {


    /**
     * 
     * @param message
     * @param tINPUT
     * @param eaiMessage
     * @param tOUTPUT
     * @param eaiFlag
     */
    @WebMethod(operationName = "TransStandardCreditToSRM", action = "http://www.example.org/TransStandardCreditToSRM/TransStandardCreditToSRM")
    @RequestWrapper(localName = "TransStandardCreditToSRM", targetNamespace = "http://www.example.org/TransStandardCreditToSRM/", className = "org.example.transstandardcredittosrm.TransStandardCreditToSRM_Type")
    @ResponseWrapper(localName = "TransStandardCreditToSRMResponse", targetNamespace = "http://www.example.org/TransStandardCreditToSRM/", className = "org.example.transstandardcredittosrm.TransStandardCreditToSRMResponse")
    public void transStandardCreditToSRM(
        @WebParam(name = "T_INPUT", targetNamespace = "")
        List<ZDSP12LOG20INPUT> tINPUT,
        @WebParam(name = "MESSAGE", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> message,
        @WebParam(name = "T_OUTPUT", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<List<ZINTZDSP12LOG20SENDING>> tOUTPUT,
        @WebParam(name = "EAIFlag", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eaiFlag,
        @WebParam(name = "EAIMessage", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eaiMessage);

}
