
package com.haier.OuterSysVendorInfoToMDM;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "OuterSysVendorInfoToMDM", targetNamespace = "http://www.example.org/OuterSysVendorInfoToMDM/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OuterSysVendorInfoToMDM {


    /**
     * 
     * @param inCOUNTRY
     * @param outVENDORCODE
     * @param retcode
     * @param systemNAME
     * @param outROWID
     * @param operateTYPE
     * @param inSTREETROOM
     * @param inREGION
     * @param outTAXCODE
     * @param tVENDORCOMPANY
     * @param inVENDORNAME
     * @param tVENDORPUR
     * @param inVENDORCODE
     * @param tVENDORBANK
     * @param viewBANKFLAG
     * @param retmsg
     * @param inACCOUNTGRPCODE
     * @param inPHONENUMBER
     * @param inTAXCODE
     * @param inPOSTALCODECITY
     */
    @WebMethod(operationName = "OuterSysVendorInfoToMDM", action = "http://www.example.org/OuterSysVendorInfoToMDM/OuterSysVendorInfoToMDM")
    @RequestWrapper(localName = "OuterSysVendorInfoToMDM", targetNamespace = "http://www.example.org/OuterSysVendorInfoToMDM/", className = "com.haier.OuterSysVendorInfoToMDM.OuterSysVendorInfoToMDM_Type")
    @ResponseWrapper(localName = "OuterSysVendorInfoToMDMResponse", targetNamespace = "http://www.example.org/OuterSysVendorInfoToMDM/", className = "com.haier.OuterSysVendorInfoToMDM.OuterSysVendorInfoToMDMResponse")
    public void outerSysVendorInfoToMDM(
        @WebParam(name = "IN_VENDOR_CODE", targetNamespace = "")
        String inVENDORCODE,
        @WebParam(name = "IN_VENDOR_NAME", targetNamespace = "")
        String inVENDORNAME,
        @WebParam(name = "IN_ACCOUNT_GRP_CODE", targetNamespace = "")
        String inACCOUNTGRPCODE,
        @WebParam(name = "IN_TAX_CODE", targetNamespace = "")
        String inTAXCODE,
        @WebParam(name = "IN_STREET_ROOM", targetNamespace = "")
        String inSTREETROOM,
        @WebParam(name = "IN_POSTAL_CODE_CITY", targetNamespace = "")
        String inPOSTALCODECITY,
        @WebParam(name = "IN_COUNTRY", targetNamespace = "")
        String inCOUNTRY,
        @WebParam(name = "IN_REGION", targetNamespace = "")
        String inREGION,
        @WebParam(name = "IN_PHONE_NUMBER", targetNamespace = "")
        String inPHONENUMBER,
        @WebParam(name = "T_VENDOR_COMPANY", targetNamespace = "")
        RSPVENDORCOMPANYTABLE tVENDORCOMPANY,
        @WebParam(name = "T_VENDOR_BANK", targetNamespace = "")
        RSPVENDORBANKTABLE tVENDORBANK,
        @WebParam(name = "T_VENDOR_PUR", targetNamespace = "")
        RSPVENDORPURTABLE tVENDORPUR,
        @WebParam(name = "SYSTEM_NAME", targetNamespace = "")
        String systemNAME,
        @WebParam(name = "VIEW_BANK_FLAG", targetNamespace = "")
        String viewBANKFLAG,
        @WebParam(name = "OPERATE_TYPE", targetNamespace = "")
        String operateTYPE,
        @WebParam(name = "RETCODE", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> retcode,
        @WebParam(name = "RETMSG", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> retmsg,
        @WebParam(name = "OUT_ROW_ID", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> outROWID,
        @WebParam(name = "OUT_VENDOR_CODE", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> outVENDORCODE,
        @WebParam(name = "OUT_TAX_CODE", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> outTAXCODE);

}
