
package com.haier.OuterSysVendorInfoToMDM;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "OuterSysVendorInfoToMDM", targetNamespace = "http://www.example.org/OuterSysVendorInfoToMDM/", wsdlLocation = "/wsdl/OuterSysVendorInfoToMDM.wsdl")
public class OuterSysVendorInfoToMDM_Service
    extends Service
{

    private final static URL OUTERSYSVENDORINFOTOMDM_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.haier.OuterSysVendorInfoToMDM.OuterSysVendorInfoToMDM_Service.class.getName());

    static {
        URL url = null;
        try {
            url = OuterSysVendorInfoToMDM_Service.class.getResource("/wsdl/OuterSysVendorInfoToMDM.wsdl");
        } catch (Exception e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:///Users/james/Workspace/snz/snz-eai-api/src/main/java/com/haier/OuterSysVendorInfoToMDM/OuterSysVendorInfoToMDM.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        OUTERSYSVENDORINFOTOMDM_WSDL_LOCATION = url;
    }

    public OuterSysVendorInfoToMDM_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OuterSysVendorInfoToMDM_Service() {
        super(OUTERSYSVENDORINFOTOMDM_WSDL_LOCATION, new QName("http://www.example.org/OuterSysVendorInfoToMDM/", "OuterSysVendorInfoToMDM"));
    }

    /**
     * 
     * @return
     *     returns OuterSysVendorInfoToMDM
     */
    @WebEndpoint(name = "OuterSysVendorInfoToMDMSOAP")
    public OuterSysVendorInfoToMDM getOuterSysVendorInfoToMDMSOAP() {
        return super.getPort(new QName("http://www.example.org/OuterSysVendorInfoToMDM/", "OuterSysVendorInfoToMDMSOAP"), OuterSysVendorInfoToMDM.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OuterSysVendorInfoToMDM
     */
    @WebEndpoint(name = "OuterSysVendorInfoToMDMSOAP")
    public OuterSysVendorInfoToMDM getOuterSysVendorInfoToMDMSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/OuterSysVendorInfoToMDM/", "OuterSysVendorInfoToMDMSOAP"), OuterSysVendorInfoToMDM.class, features);
    }

}
